name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - 
        name: Cancel Previus Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
    
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
              fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
              node-version: 18
        - name: Install dependencies
          run: yarn install
        - name: Lint
          run: yarn lint

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test

  docker:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push, API
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/api/Dockerfile
          push: true
          tags: alex2117/eva-api:latest
      -
        name: Build and push, DB
        uses: docker/build-push-action@v4
        with:
          context: ./docker/database
          file: ./docker/database/Dockerfile
          push: true
          tags: alex2117/eva-db:latest
